name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull bkimminich/juice-shop

      - name: Run Docker Image
        run: docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

 