name: DevSecOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Pull Docker Image
      - name: Pull Docker Image
        run: docker pull bkimminich/juice-shop

      # Step 3: Run Docker Image
      - name: Run Docker Image
        run: docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop

  