name: Dynamic Application Security Testing
on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Juice Shop
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          sleep 30

      - name: Run OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://localhost:3000'

      - name: Cleanup Docker container
        if: always()
        run: |
          docker stop juice-shop
          docker rm juice-shop
 