name: Dynamic Application Security Testing
on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Juice Shop
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          sleep 30

      - name: Run OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.7.0
        env:
          USE_NETWORK_HOST: 'false'
        with:
          target: 'http://host.docker.internal:3000'
          docker_run_options: '--add-host=host.docker.internal:host-gateway'
