name: SCA Pipeline

on:
  push:
    branches:
      - main

jobs:
  sca-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      
      - name: Scan Dependencies with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bkimminich/juice-shop
