name: SonarQube Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: 'http://localhost:9000'
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Install SonarScanner
          npm install -g sonar-scanner

          # Run SonarScanner
          sonar-scanner \
            -Dsonar.projectKey=juice-shop \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_LOGIN

      - name: Build Docker Image
        run: |
          docker build -t juice-shop:latest .


      - name: Deploy Application
        run: |
          docker stop juice-shop || true
          docker rm juice-shop || true
          docker run -d -p 3000:3000 --name juice-shop juice-shop:latest
          sleep 30


