name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Setup Java (if required)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Run SonarQube Scanner
      - name: Run SonarQube Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=my_project_key
            -Dsonar.organization=my_organization
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
